DROP TABLE IF EXISTS votes CASCADE;
CREATE TABLE votes (
  id SERIAL PRIMARY KEY NOT NULL,
  rank INTEGER NOT NULL,
  option_id INTEGER REFERENCES options(id) ON DELETE CASCADE,
  voter_name VARCHAR(255)
);
